### ISSUE TITLE
ARM64 based MacOS Support

### ISSUE THREAD

**Issue by yunussandikci** [hazelcast/hazelcast-cloud-cli#8]
Apple just introduced their Apple Silicon M1 chip which based on ARM. We should support this architecture and add binary for our further releases.
`Golang` also introduced how to cross-compile go applications for this architecture on their repository. [Apple Silicon](https://github.com/golang/go/wiki/GoArm#apple-silicon)

**Comment by jerrinot** [comment]
please include Linux/ARM64 too. thanks!

**Comment by yunussandikci** [comment]
@jerrinot We already have this, you can check it from [Releases](https://github.com/hazelcast/hazelcast-cloud-cli/releases/tag/v1.2.1).
